version: '2'
services:
  apache:
    build: .
    volumes:
      - ./www:/var/www
    ports:
      - "443:443"
      - "8001:80"

  cert:
    image: stakater/ssl-certs-generator:1.0
    volumes:
      - ./etc/letsencrypt/live:/certs

networks:
  apache:
  core_core:
    external: true
